spring.application.name=BaiTap01

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/employees
spring.datasource.username=root
spring.datasource.password=sapassword

app.datasource.driver=org.mariadb.jdbc.Driver
app.datasource.url=jdbc:mariadb://localhost:3306/employees
app.datasource.username=root
app.datasource.password=sapassword
